/bizon2/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/bizon2/arm_group_controller:
  ros__parameters:
    joints:
      - bizon2rev1
      - bizon2pris1
      - bizon2rev2
      - bizon2rev3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

/bizon2/hand_group_controller:
  ros__parameters:
    joints:
      - bizon2gripper_finger1_joint
      - bizon2gripper_finger2_joint
      - bizon2gripper_finger3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity