FROM nvcr.io/nvidia/tensorrt:24.04-py3

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
    python3 \
    python3-pip \
    git

RUN pip3 install cmake --upgrade
WORKDIR /workspace

ENV CUDNN_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDNN_DIR/lib64:$LD_LIBRARY_PATH

ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

RUN apt-get install libgtk* libspdlog-dev libfmt-dev libboost-dev ffmpeg libavformat-dev libavcodec-dev libswscale-dev pybind11-dev -y 

WORKDIR /workspace
RUN git clone https://github.com/opencv/opencv.git && git clone https://github.com/opencv/opencv_contrib.git && cd opencv && mkdir build
WORKDIR /workspace/opencv/build
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs/libcuda.so \
    -D WITH_CUDA=ON \
    -D WITH_CUDNN=ON \
    -D OPENCV_DNN_CUDA=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D WITH_CUBLAS=1 \
    -D WITH_CUFFT=ON \
    -D WITH_CUBLAS=1 \
    -D WITH_NVCUVID=ON \
    -D BUILD_opencv_cudacodec=ON \
    -D CUDA_ARCH_BIN=8.9 \
    -D WITH_OPENGL=ON \
    -D WITH_NVCUVID=ON \
    -D WITH_FFMPEG=ON \
    -D WITH_GSTREAMER=ON \
    -D WITH_TBB=ON \
    -D BUILD_TESTS=OFF \
    -D BUILD_PERF_TESTS=OFF \
    -D BUILD_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=/workspace/opencv_contrib/modules ..

RUN make -j$(nproc) && make install
RUN pip3 install torch torchvision --upgrade --force-reinstall

RUN apt-get update && apt-get upgrade -y
RUN pip3 install onnxslim onnxruntime-gpu matplotlib tqdm requests psutil
RUN pip3 install "numpy<2"

WORKDIR /workspace
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | gpg --dearmor > /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt-get update && apt-get install -y ros-humble-desktop
RUN apt-get install -y python3-colcon-common-extensions python3-rosdep python3-rosinstall python3-vcstool
RUN rosdep init
RUN rosdep update




RUN apt-get install -y \
    libpcap-dev \
    python3-pip \
    libyaml-cpp-dev \
    libzmq3-dev \
    ros-humble-moveit* \
    ros-humble-cont* \
    ros-humble-ros2-cont* \
    ros-humble-bond* \
    ros-humble-diagnostic-updater* \
    ros-humble-nav2-common

RUN apt-get update && apt-get upgrade -y

#WORKDIR /workspace
#RUN git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git && cd BehaviorTree.CPP && git checkout cdaca9c && mkdir build
#WORKDIR /workspace/BehaviorTree.CPP/build
#RUN cmake -DBTCPP_ENABLE_ZMQ=ON .. && \
#    make -j$(nproc) && \
#    make install


#RUN apt-get update && apt-get upgrade -y
#COPY ./dockerutils/fastdds.xml ~/.ros/fastdds.xml